/* $Id$
 * IRC-2 user commands
 * 
 * Copyright (c) 2001,2002,2003 Simon Butcher <pickle@alien.net.au>
 * Copyright (c) 2001,2002,2003 KineIRCd Development Team
 * (See DEV-TEAM file for details)
 *
 * This file is a part of KineIRCd.
 * 
 * KineIRCd is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * KineIRCd is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with KineIRCd; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 *
 * DO NOT EDIT THIS FILE   (src/mod_irc2user/commands.cpp)
 * 
 * It has been AutoGen-ed  Monday March 31, 2003 at 05:01:24 PM EST
 * From the definitions    src/mod_irc2user/commands.def
 * and the template file   src/mod_irc2user/commands.cpp.tpl
 */

#ifndef _SRC_MOD_IRC2USER_COMMANDS_H_
# define _SRC_MOD_IRC2USER_COMMANDS_H_ 1

# include <kineircd/kineircdconf.h>
# include <kineircd/languages.h>
# include <string>
# ifdef KINE_STL_HAS_HASH
#  include <hash_map>
# else
#  include <map>
# endif

namespace Kine {
   namespace mod_irc2user {
      class Commands {
       private:
	 // A table holding the built-in commands we always support
	 struct preInitCommand_type {
	    const char* const commandName;		// Name of the command
	    const unsigned char defaultPenalty;		// Initial penalty rate
	    const Kine::Languages::tagID_type* const 
	      helpUsage;				// Command usage hint
	    const Kine::Languages::tagID_type* const 
	      helpInfo;					// Detailed help tag
	 } static const preInitCommands[];

       public:
	 // A 'command descriptor' for our commands table.
	 struct CommandInfo {
	    unsigned char penalty;			// Set penalty rate
	    const Kine::Languages::tagID_type* const
	      helpUsage;				// Command usage hint
	    const Kine::Languages::tagID_type* const
	      helpInfo;					// Detailed help tag
	    unsigned long long callCount;		// # times used
	    
	    // Copy constructor to aid in initialisation
	    CommandInfo(const preInitCommand_type& info)
	      : penalty(info.defaultPenalty),
	        helpUsage(info.helpUsage),
	        helpInfo(info.helpInfo),
	        callCount(0)
	      {};
	 };
	 
       private:
	 // A list of commands
# ifdef KINE_STL_HAS_HASH
	 typedef std::hash_map < std::string, CommandInfo > commandsList_type;
# else
	 typedef std::map < std::string, CommandInfo > commandsList_type;
# endif
	 commandsList_type commandsList;
	 
	 // Our single instance
	 static Commands* instance;
	 
	 // Constructor
	 Commands(void);
	 
       public:
	 // Destructor
	 ~Commands(void)
	   {};
	 
	 // Create the single instance of this class
	 static void initInstance(void);
	 
	 // Grab the single instance of ourself
	 static Commands& getInstance(void)
	   { return *instance; };
	 
	 // Find a command in the command list
	 const CommandInfo* const findCommand(const std::string& name);
      };
   }; // namespace mod_irc2user
}; // namespace Kine
   
#endif // _SRC_MOD_IRC2USER_COMMANDS_H_
   
