# $Id$
# Little makefile for developers wishing to bootstrap the package
#

.PHONY: __bs__ autoconf

__bs__:
	@echo "Do not make directly from Makefile.bs!"
	@echo "This file is intended for developers only."


# Create AutoConf files from templates
autoconf: autoconf/configure.in
	autoconf -I autoconf -o configure autoconf/configure.in
	-chmod 755 configure
	autoheader --localdir=autoconf autoconf/configure.in \
		>include/kineircd/kineircdconf.h.in
