[+ AutoGen5 template h cpp +]
[+ CASE (suffix) +]
[+ == h +]
/* langtags.h - Language tag definitions
 * 
 * DO NOT EDIT THIS FILE! It is automatically generated from langtags.tpl.
 * Edit langtags.def instead.
 * 
 * Copyright (c) 2001,2002 AustHex Development Team
 * (See DEV-TEAM file for details)
 *
 * This file is a part of AustHex.
 * 
 * AustHex is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * AustHex is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with AustHex; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef _LANGTAGS_H_
# define _LANGTAGS_H_

class LangTags {
 public:
   /* Corresponding numbers for the language data vector
    * WARNING!!! This list is kept in sync with the list in
    * the accompanying C++ file by being automatically generated.
    * DO NOT EDIT THIS!
    */
   enum tag_t {[+ FOR langtags +]
        [+tag_name+],[+ ENDFOR langtags +]
	_END_
   };
};

#endif

/* End of generated output */
[+ == cpp +]
/* langtags.cpp - Language tag definitions
 * 
 * DO NOT EDIT THIS FILE! It is automatically generated from langtags.tpl.
 * Edit langtags.def instead.
 * 
 * Copyright (c) 2001,2002 AustHex Development Team
 * (See DEV-TEAM file for details)
 *
 * This file is a part of AustHex.
 * 
 * AustHex is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * AustHex is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with AustHex; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#include "austhex/austhexconf.h"

#include "austhex/lang.h"


namespace Lang {
   /* This is a list of language tags so that the language parser
    * knows where to shove the language data.
    * WARNING!!! This list is kept in sync with the list in
    * the accompanying header file by being automatically generated.
    * DO NOT EDIT THIS!
    */
   Lang::languageTagsStruct languageTags[LangTags::_END_] =
     {[+ FOR langtags "," +]
          { "[+tag_name+]",
	    [+tag_required+], [+tag_oneword+]
	  }[+ ENDFOR langtags +]
     };
}

/* End of generated output */
[+ ESAC +]
