[+ AutoGen5 template h cpp +]
[+ CASE (suffix) +]
[+ == h +]
/* langtags.h - Language tag definitions
 * 
 * DO NOT EDIT THIS FILE! It is automatically generated from langtags.tpl.
 * Edit langtags.def instead.
 */

#ifndef __LANGTAGS_H_
# define __LANGTAGS_H_

class LangTags {
 public:
   /* Corresponding numbers for the language data vector
    * WARNING!!! This list is kept in sync with the list in
    * the accompanying C++ file by being automatically generated.
    * DO NOT EDIT THIS!
    */
   enum tag_t {[+ FOR langtags +]
        [+tag_name+],[+ ENDFOR langtags +]
	_END_
   };
};

#endif

/* End of generated output */
[+ == cpp +]
/* langtags.cpp - Language tag definitions
 * 
 * DO NOT EDIT THIS FILE! It is automatically generated from langtags.tpl.
 * Edit langtags.def instead.
 */

#include "autoconf.h"

#include "lang.h"


namespace Lang {
   /* This is a list of language tags so that the language parser
    * knows where to shove the language data.
    * WARNING!!! This list is kept in sync with the list in
    * the accompanying header file by being automatically generated.
    * DO NOT EDIT THIS!
    */
   Lang::languageTagsStruct languageTags[LangTags::_END_] =
     {[+ FOR langtags "," +]
          { "[+tag_name+]",
	    [+tag_required+], [+tag_oneword+]
	  }[+ ENDFOR langtags +]
     };
}

/* End of generated output */
[+ ESAC +]
