[+ AutoGen5 template h +]
/* regnumerics.h
 * Tiny list of numerics potentially used during the registration of a client
 * 
 * DO NOT EDIT THIS FILE! It is automatically generated from regnumerics.h.tpl.
 * Edit irc2numerics.def/regnumerics.h.tpl instead.
 *
 * Copyright (c) 2002 Alien Internet Services
 *
 * This file is a part of KineIRCd.
 * 
 * KineIRCd is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * KineIRCd is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with KineIRCd; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef _SRC_LIB_REGNUMERICS_H_
# define _SRC_LIB_REGNUMERICS_H_

enum {
#error "we must loop here in the template file and rip out appropriate numerics"
};

#endif

